arches/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('task.urls', namespace='task')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

task/urls.py
from django.urls import path

from . import views

app_name = 'task'
urlpatterns = [
    path('', views.index, name='index'),
    path('answer_list/', views.answer, name='answer_list'),
    path('task/<slug:slug>/', views.task_detail, name='task_detail'),
]

task/models.py
from django.db import models


class Task(models.Model):
    slug = models.SlugField(unique=True)
    answer = models.TextField()
    image = models.ImageField(
        'Картинка',
        upload_to='task/',
        blank=True
    )

    class Meta:
        default_related_name = 'task'

task/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('slug', 'answer', 'image')

task/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from .models import Task


def get_paginator(request, obj_list):
    paginator = Paginator(obj_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'task/index.html'
    return render(request, template)


def answer(request):
    template = 'task/answer_list.html'
    tasks = Task.objects.all()
    page_obj = get_paginator(request, tasks)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def task_detail(request, slug):
    task = get_object_or_404(Task, slug=slug)
    templates = {
        '2_43_2': 'task/2_43_2.html',
        '2_43_3': 'task/2_43_3.html',
        '2_43_4': 'task/2_43_4.html',
        '26_17': 'task/26_17.html',
        '26_18': 'task/26_18.html',
        '26_19': 'task/26_19.html',
        '26_20': 'task/26_20.html',
    }
    context = {
        'task': task,
    }
    return render(request, templates[slug], context)

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Арки
      {% endblock %}
    </title>
    {% block style %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    {% endblock style %}
  </head>
  <body>
    <header>
      {% block header %}
      {% include 'includes/header_for_tasks.html' %}
      {% endblock header %}
    </header>

    <main>
      {% block content %}
        Контент не подвезли
      {% endblock content %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
    {% block script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    {% endblock script %}
  </body>
</html>

templates/includes/comment_26_17.html
<div style="margin-top:50px; margin-left:50px;">
<h3>
  <p class="fst-italic fw-weight-normal"> Ответ: R = 0,2 V Н.</p>
</h3>
</div>

templates/includes/comment_26_18.html
<div style="margin-top:50px; margin-left:50px;">
<h3>
  <p class="fst-italic fw-weight-normal"> Ответ: F1 = 2372 Н; F2 = 686 Н.</p>
</h3>
</div>

templates/includes/comment_26_19.html
<div style="margin-top:50px; margin-left:50px;">
<h3>
  <p class="fst-italic fw-weight-normal"> Ответ: T1 = 1676 Н; T2 = 1956 Н.</p>
</h3>
</div>

templates/includes/comment_26_20.html
<div style="margin-top:50px; margin-left:50px;">
<h3>
  <p class="fst-italic fw-weight-normal"> Ответ: T = 10000 Н. Максимум значения T следует из максимального значения v и проекции
g в нижней точке.</p>
</h3>
</div>

templates/includes/comments.html
<div style="margin-top:50px; margin-left:50px;">
<h3>
<form oninput="out.value=(-p.value/1.414214).toFixed(2),
	out2.value=(p.value/1.414214).toFixed(2)">
	<p>P: <input type="text" name="p" size="6" value="0"> н</p>
	<p>Ra: <output name="out">0</output> н</p>
  <p>Rb: <output name="out2">0</output> н</p>
</form>
    </div>
  </div>
</h3>
</div>

templates/includes/comments2.html
<div style="margin-top:50px; margin-left:50px;">
<h3><form oninput="out.value=(-p.value/1.414214).toFixed(2),
	out2.value=(p.value/1).toFixed(2),
	out3.value=(p.value/1.414214).toFixed(2)">
	<p>P: <input type="text" name="p" size="6" value="0"> н</p>
	<p>Ra: <output name="out">0</output> н</p>
  <p>Rb: <output name="out2">0</output> н</p>
  <p>Rc: <output name="out3">0</output> н</p>
</form>
    </div>
  </div>
</h3>
</div>

templates/includes/comments3.html
<div style="margin-top:50px; margin-left:50px;">
<h3>
<form oninput="out.value=(-p.value/1.414214).toFixed(2),
	out2.value=(p.value/1).toFixed(2),
	out3.value=(p.value/1).toFixed(2),
	out4.value=(p.value/1.414214).toFixed(2)">
	<p>P: <input type="text" name="p" size="6" value="0"> н</p>
	<p>Ra: <output name="out">0</output> н</p>
  <p>Rb: <output name="out2">0</output> н</p>
  <p>Rc: <output name="out3">0</output> н</p>
  <p>Rd: <output name="out4">0</output> н</p>
</form>
    </div>
  </div>
</h3>
</div>

templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Камне</span>ломы</p>
  </div>
</footer>

templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightgray">
    <div class="container">
      <a class="navbar-brand" href="{% url 'task:index' %}">
        <div class="position-absolute top-5 start-50 translate-middle">
        <span style="color:red">Камне</span>ломы</div>
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'task:answer_list' %}"
          >
            Задачи
          </a>
        </li>
      {% endwith %}
      </ul>
    </div>
  </nav>
</header>

templates/includes/header_for_list.html
<style>
        /* Carousel styling */
        #introCarousel,
        .carousel-inner,
        .carousel-item,
        .carousel-item.active {
          height: 100vh;
        }

        .carousel-item:nth-child(1) {
          background-image:
            url('https://drive.google.com/uc?export=view&id=1s9eNAf0JmnvKL1xVuRzq8aLucOagVApk');
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center center;
        }


        /* Height for devices larger than 576px */
        @media (min-width: 992px) {
          #introCarousel {
            margin-top: -58.59px;
          }
          #introCarousel,
          .carousel-inner,
          .carousel-item,
          .carousel-item.active {
            height: 50vh;
          }
        }

        .navbar .nav-link {
          color: #fff !important;
        }
      </style>
<nav class="navbar navbar-expand-lg navbar-dark d-none d-lg-block"
     style="z-index: 2000; background-color: rgba(0, 0, 0, 0.6);">

        <div class="container-fluid">
          <a class="navbar-brand nav-link"
             href="{% url 'task:index' %}">
            <strong>Камнеломы</strong>
          </a>


            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item active">
                <a class="nav-link" aria-current="page" href="#intro">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow"
                  target="_blank">Learn Bootstrap 5</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://mdbootstrap.com/docs/standard/" target="_blank">Download MDB UI KIT</a>
              </li>
            </ul>


        </div>

      </nav>
</div>
      <!-- Navbar -->

      <!-- Carousel wrapper -->
      <div id="introCarousel" class="carousel slide carousel-fade shadow-2-strong" data-mdb-ride="carousel">
        <!-- Inner -->
        <div class="carousel-inner">
          <!-- Single item -->
          <div class="carousel-item active">
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">

            </div>
          </div>

        </div>
        <!-- Inner -->
      </div>
      <!-- Carousel wrapper -->

templates/includes/header_for_tasks.html
<style>
        /* Carousel styling */
        #introCarousel,
        .carousel-inner,
        .carousel-item,
        .carousel-item.active {
          height: 100vh;
        }

        .carousel-item:nth-child(1) {
          background-image:
            url('https://drive.google.com/uc?export=view&id=1s9eNAf0JmnvKL1xVuRzq8aLucOagVApk');
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center center;
        }


        /* Height for devices larger than 576px */
        @media (min-width: 992px) {
          #introCarousel {
            margin-top: -58.59px;
          }
          #introCarousel,
          .carousel-inner,
          .carousel-item,
          .carousel-item.active {
            height: 50vh;
          }
        }

        .navbar .nav-link {
          color: #fff !important;
        }
      </style>
<nav class="navbar navbar-expand-lg navbar-dark d-none d-lg-block"
     style="z-index: 5; background-color: rgba(0, 0, 0, 0.6);">

        <div class="container-fluid">
          <a class="navbar-brand nav-link"
             href="{% url 'task:index' %}">
            <strong>Камнеломы</strong>
          </a>


            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item active">
                <a class="nav-link" aria-current="page"
                   href={% url 'task:answer_list' %}>Задачи</a>
              </li>
            </ul>


        </div>

      </nav>
</div>
      <!-- Navbar -->

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/task/26_17.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% endblock title %}
{% block content %}
<main>
  <h3>
  <p class="text-center">Задача №{{task.slug}}</p></h3>
  {% thumbnail task.image "826x734" crop="center" upscale=False as im %}
  <img class="rounded mx-auto d-block" src="{{ im.url }}" alt="Responsive image" >
  {% endthumbnail %}
  <article class="col-12 col-md-9" style="margin-left:50px;">
    <p class="fw-weight-bold fs-4">
      {{ task.answer }}
    </p>
  </article>

  {% include 'includes/comment_26_17.html' %}
  </div>
  <div style="margin-left:50px;">
  <a
    href="https://drive.google.com/file/d/130kkxiSq1C3j2wdTap7FRbE4P3pUIPqB/view?usp=sharing" download="Zadacha_21_17.pdf" target="_blank" class="fs-4 link-offset-5 link-underline link-underline-opacity-0">Подробное решение</a>
</div>
</main>

{% endblock content %}

templates/task/26_18.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% endblock title %}
{% block content %}
<main>
    <h3>
  <p class="text-center">Задача №{{task.slug}}</p></h3>
  {% thumbnail task.image "826x734" crop="center" upscale=False as im %}
  <img class="rounded mx-auto d-block" src="{{ im.url }}" alt="Responsive image" >
  {% endthumbnail %}
  <article class="col-12 col-md-9" style="margin-left:50px;">
    <p class="fw-weight-bold fs-4">
      {{ task.answer }}
    </p>
  </article>

  {% include 'includes/comment_26_18.html' %}
  </div>
  <div style="margin-left:50px;">
  <a
    href="https://drive.google.com/file/d/1OQ4e0riAA8Lia6PwOCe9j5oES3y8lZkI/view?usp=sharing" download="Zadacha_21_17.pdf" target="_blank" class="fs-4 link-offset-5 link-underline link-underline-opacity-0">Подробное решение</a>
</div>
</main>

{% endblock content %}

templates/task/26_19.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% endblock title %}
{% block content %}
<main>
  <h3>
  <p class="text-center">Задача №{{task.slug}}</p></h3>
  {% thumbnail task.image "826x734" crop="center" upscale=False as im %}
  <img class="rounded mx-auto d-block" src="{{ im.url }}" alt="Responsive image" >
  {% endthumbnail %}
  <article class="col-12 col-md-9" style="margin-left:50px;">
    <p class="fw-weight-bold fs-4">
      {{ task.answer }}
    </p>
  </article>

  {% include 'includes/comment_26_19.html' %}
  </div>
  <div style="margin-left:50px;">
  <a
    href="https://drive.google.com/file/d/1FvzlusxQv5D3D9WymQv-GD4UsUc36qdE/view?usp=sharing" download="Zadacha_21_17.pdf" target="_blank" class="fs-4 link-offset-5 link-underline link-underline-opacity-0">Подробное решение</a>
</div>
</main>

{% endblock content %}

templates/task/26_20.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% endblock title %}
{% block content %}
<main>
  <h3>
  <p class="text-center">Задача №{{task.slug}}</p></h3>
  {% thumbnail task.image "826x734" crop="center" upscale=False as im %}
  <img class="rounded mx-auto d-block" src="{{ im.url }}" alt="Responsive image" >
  {% endthumbnail %}
  <article class="col-12 col-md-9" style="margin-left:50px;">
    <p class="fw-weight-bold fs-4">
      {{ task.answer }}
    </p>
  </article>

  {% include 'includes/comment_26_20.html' %}
  </div>
  <div style="margin-left:50px;">
  <a
    href="https://drive.google.com/file/d/1sHTJzsXZ5TO_JzSyPn47GTFSyucqOcBQ/view?usp=sharing" download="Zadacha_21_17.pdf" target="_blank" class="fs-4 link-offset-5 link-underline link-underline-opacity-0">Подробное решение</a>
</div>
</main>

{% endblock content %}

templates/task/2_43_2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Title</title>
  </head>
  <body>

  </body>
</html>

templates/task/2_43_3.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% endblock title %}
{% block content %}
<main>
  <h3>
  <p class="text-center">Задача №{{task.slug}}</p></h3>
  {% thumbnail task.image "419x237" crop="center" upscale=False as im %}
  <img class="rounded mx-auto d-block" src="{{ im.url }}">
  {% endthumbnail %}
  <article class="col-12 col-md-9" style="margin-left:50px;">
    <p class="fw-weight-bold fs-4">
      {{ task.answer }}
    </p></article>
    <button class="btn btn-success" type="button" data-bs-toggle="offcanvas"
          data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" style="margin-left:50px;">Разновидности задачи(2, 3, 4 арки)</button>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 id="offcanvasRightLabel">Разновидности задачи(2, 3, 4 арки)</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
  </div>
  <div class="offcanvas-body">
    <p><a class="link-offset-2 link-underline link-underline-opacity-0" href={% url 'task:task_detail' '2_43_2' %}> 2 арки
    </a></p>
    <p><a  class="link-offset-2 link-underline link-underline-opacity-0"
           href={% url 'task:task_detail' '2_43_3' %}> 3 арки
    </a></p>
    <p><a  class="link-offset-2 link-underline link-underline-opacity-0"
           href={% url 'task:task_detail' '2_43_4' %}> 4 арки
    </a></p>
  </div>
</div>

  {% include 'includes/comments2.html' %}
  </div>
  <div style="margin-left:50px;">
  <a
    href="https://drive.google.com/file/d/130kkxiSq1C3j2wdTap7FRbE4P3pUIPqB/view?usp=sharing" download="Zadacha_21_17.pdf" target="_blank" class="fs-4 link-offset-5 link-underline link-underline-opacity-0">Подробное решение</a>
</div>
</main>
{% endblock content %}

templates/task/2_43_4.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% endblock title %}
{% block content %}
<main>
  <h3>
  <p class="text-center">Задача №{{task.slug}}</p></h3>
  {% thumbnail task.image "583x237" crop="center" upscale=False as im %}
  <img class="rounded mx-auto d-block" src="{{ im.url }}">
  {% endthumbnail %}
  <article class="col-12 col-md-9" style="margin-left:50px;">
    <p class="fw-weight-bold fs-4">
      {{ task.answer }}
    </p>
  </article>
  <button class="btn btn-success" type="button" data-bs-toggle="offcanvas"
          data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" style="margin-left:50px;">Разновидности задачи(2, 3, 4 арки)</button>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 id="offcanvasRightLabel">Разновидности задачи(2, 3, 4 арки)</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
  </div>
  <div class="offcanvas-body">
    <p><a class="link-offset-2 link-underline link-underline-opacity-0" href={% url 'task:task_detail' '2_43_2' %}> 2 арки
    </a></p>
    <p><a  class="link-offset-2 link-underline link-underline-opacity-0"
           href={% url 'task:task_detail' '2_43_3' %}> 3 арки
    </a></p>
    <p><a  class="link-offset-2 link-underline link-underline-opacity-0"
           href={% url 'task:task_detail' '2_43_4' %}> 4 арки
    </a></p>
  </div>
</div>
  {% include 'includes/comments3.html' %}
  </div>
  <div style="margin-left:50px;">
  <a
    href="https://drive.google.com/file/d/130kkxiSq1C3j2wdTap7FRbE4P3pUIPqB/view?usp=sharing" download="Zadacha_21_17.pdf" target="_blank" class="fs-4 link-offset-5 link-underline link-underline-opacity-0">Подробное решение</a>
</div>
</main>
{% endblock content %}

templates/task/answer_list.html
{% extends 'base.html' %}
{% load static %}
{% include 'includes/head.html' %}
{% block title %}
  Задания
{% endblock title %}
{% block style %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
{% endblock style %}
{% block header %}
      {% include 'includes/header_for_list.html' %}
{% endblock header %}
{% block content %}
<h1><span style="color:black"><p class="text-center">Задачи</p></span>
  </h1>
  {% for task in page_obj %}
    {% include 'task/test_task.html' %}
    {% if not forloop.last %}
    {% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock content %}

templates/task/index.html
{% extends 'base.html' %}
{% include 'includes/head.html' %}
{% load static %}
  {% block title %}
  Последние обновления на сайте
{% endblock title %}
{% block style %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

{% endblock style %}

{% block content %}
  <div class="text">
    <h2>
<a href="{% url 'task:answer_list'%}" class="text-decoration-none"><span
  style="color:white">Ломать
  камни</span>
</a></h2>
  </div>
<div class="overlay"></div>
<div class="BG">
  <img src="{% static 'img/krasivyj-zakat-na-more-i-kamni-bolshie.jpg' %}" alt="">
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock script %}

templates/task/task.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Title</title>
  </head>
  <body>

  </body>
</html>

templates/task/test_task.html
{% load thumbnail %}
{% block title %}
{% endblock title %}
{% block content %}
<main>
  <div class="row justify-content-center">
    <div class="col-md-6 col-xl-6">
  <div class="card bg-body shadow p-3 border-success mb-5 border-2 rounded-3" >
    <p class="text-start  fw-weight-bold"><strong>Задача № {{task.slug}}</strong></p>
  {% thumbnail task.image "826x734" crop="center" upscale=False as im %}
  <img class="rounded mx-auto d-block" src="{{ im.url }}" alt="Responsive image" >
  {% endthumbnail %}
  <div class="card-body">
    <h5 class="card-title">Дано: </h5>
    <p class="card-text">{{ task.answer }}</p>

  <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
  <li class="list-group-item">
    <a href={% url 'task:task_detail' task.slug %}>
    <button type="button" class="btn btn-success">Подробнее</button> </a>
  </li>
        </ul>
      </aside>
  </div>
    <p class="card-text"><small class="text-muted"></small></p>
  </div>
</div>
  </div>
  </div>

</main>
{% endblock content %}